services:
  postgres:
    image: postgres:15-alpine
    container_name: sdas-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sdas_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sdas_password}
      POSTGRES_DB: ${POSTGRES_DB:-sdas_db}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: sdas-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-sdas_admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-sdas_password}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: sdas-keycloak
    restart: always
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HTTP_ENABLED: 'true'
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-sdas_admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-sdas_admin}
    ports:
      - '8080:8080'
    command: start-dev
    depends_on:
      - postgres

volumes:
  postgres_data:
  mongodb_data:
